// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFbViWtBgXIXItN4Ei0O340e0QqlTdPBk',
    appId: '1:415680926280:android:a8df82f8e9d3ed1950be7d',
    messagingSenderId: '415680926280',
    projectId: 'linedup-eade0',
    storageBucket: 'linedup-eade0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB97oFWSsPqdTHCMiy41OIyluk127qHNtU',
    appId: '1:415680926280:ios:2e5eceebe244174150be7d',
    messagingSenderId: '415680926280',
    projectId: 'linedup-eade0',
    storageBucket: 'linedup-eade0.appspot.com',
    androidClientId: '415680926280-c1n86s9mlp3kfn6cljoo2qn7j9u7k1hh.apps.googleusercontent.com',
    iosClientId: '415680926280-vf1n455b5aodmhhdj2i0i8nd0mricgp4.apps.googleusercontent.com',
    iosBundleId: 'com.linedup.linedupApp',
  );
}
